---
# Shared configuration for all tests.

instances:
  - region: us-east-1
    instance: autotest-aurora-mysql-56
  - region: us-east-1
    instance: autotest-psql-10
  - region: us-west-2
    instance: autotest-mysql-57
  - region: us-west-2
    instance: autotest-aurora-psql-11
  - region: us-west-2
    instance: no-such-instance
