FROM alpine:latest

COPY ./rds_exporter  /bin/

RUN apk update && \
  apk add ca-certificates --no-cache && \
  update-ca-certificates && \
  rm -f /var/cache/apk/*

EXPOSE      9042
ENTRYPOINT  [ "/bin/rds_exporter", "--config.file=/etc/rds_exporter/config.yml" ]
